name: "Google Ping"
on:
  push:
    branches:
      - main

jobs:
  goole_ping:
    name: Ping 8.8.8.8
    runs-on: ubuntu-latest
  
    steps:
       - name: Ping 
         #run: ping 8.8.8.8 -c 5
         run: ping 127.0.0.1 -c 5
         
       - name: Resolv 
         run: dig google.com
